CREATE TABLE CUSTOMER
(
id int NOT NULL PRIMARY KEY,
name varchar(45) NOT NULL,
surname varchar(45)
);

CREATE TABLE USERS
(
id int NOT NULL PRIMARY KEY,
login varchar(20) NOT NULL,
password varchar(20) NOT NULL
);

CREATE TABLE ROLES
(
id int NOT NULL PRIMARY KEY,
role varchar(20) NOT NULL
);

CREATE TABLE USER_ROLES
(
user_id int NOT NULL,
role_id int NOT NULL,
CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES USERS(id),
CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES ROLES(id)
);

INSERT INTO USERS(ID, LOGIN, PASSWORD) VALUES (1, 'admin', '222222');
INSERT INTO USERS(ID, LOGIN, PASSWORD) VALUES (2, 'moder', '111111');

INSERT INTO ROLES(ID, ROLE) VALUES (1, 'admin');
INSERT INTO ROLES(ID, ROLE) VALUES (2, 'moderator');

INSERT INTO USER_ROLES(user_id, role_id) VALUES (1, 1);
INSERT INTO USER_ROLES(user_id, role_id) VALUES (2, 2);